require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'storage/**/*'
    - 'public/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'bin/bundle'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Metrics/BlockLength:
  Max: 40

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
