AllCops:
  Exclude:
    - 'config/**/*'
    - 'storage/**/*'
    - 'public/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'bin/bundle'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines


Metrics/AbcSize:
  Max: 36
  Exclude:
    - 'app/workers/*'


Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 6
  Exclude:
    - 'app/controllers/movies_controller.rb'
    - 'app/workers/movie_worker.rb'
    - 'db/migrate/20210617112047_add_columns_to_movies.rb'


Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/movies_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'app/workers/movie_worker.rb'
    - 'config/application.rb'
    - 'db/migrate/20210528122342_create_movies.rb'
    - 'db/migrate/20210617112047_add_columns_to_movies.rb'
    - 'db/migrate/20210617122232_create_actors.rb'
    - 'db/migrate/20210617124120_add_actor_to_credits.rb'
    - 'db/migrate/20210617124129_add_movie_to_credits.rb'
    - 'db/migrate/20210617124339_drop_credits.rb'
    - 'db/migrate/20210617124615_create_credits.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

#RSpec/ContextWording:
#  Prefixes:
#    - when
#    - with
#    - without
#    - if
#    - and
